# tasks
  # remove the user named chathura
  # remove the apache2

---
  - hosts: all
    tasks:
      - name: remove the user named chathura
        user:
          name: chathura
          state: absent
      - name: remove the apache2
        service:
          name: httpd
          state: stopped
          enabled: no