- hosts: dev
  tasks:
    - name: Download TomCat from the dlcdn
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.89/bin/apache-tomcat-9.0.89.tar.gz
        dest: /root

    - name: Extract the downloaded file
      command: tar -zxvf apache-tomcat-9.0.89.tar.gz
    
    # unarchive:
    #   src: /root/apache-tomcat-9.0.76.tar.gz
    #   dest: /root

    - name: rename the TomCat directory
      command: mv apache-tomcat-9.0.89 tomcat

    - name: install java
      command: yum install java-1.8.0-openjdk -y

    - name: setting the roles in tomcat-user.xml file
      template:
        src: tomcat-users.xml
        dest: /root/tomcat/conf/tomcat-users.xml

    - name: delete the lines in context.xml file
      template:
        src: context.xml
        dest: /root/tomcat/webapps/manager/META-INF/context.xml

    - name: start the tomcat service
      shell: nohup /root/tomcat/bin/startup.sh

    