---
- hosts: all
  tasks:
    - name: Install GIT on RedHat
      yum: 
        name: git
        state: present
      when: ansible_os_family == "RedHat"

    - name: install Git on Debian (Ubuntu)
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"
...